export type CourseStatus = "active" | "upcoming" | "completed";

/* ─────────────────────────────
   CLASS
───────────────────────────── */
export interface CourseClass {
    classId?: string; // Optional for creation, will be generated by backend
    title: string;
    session: string;
    completed?: boolean;
}

/* ─────────────────────────────
   MODULE
───────────────────────────── */
export interface CourseModule {
    moduleId?: string; // Optional for creation, will be generated by backend
    title: string;
    classes: CourseClass[];
}

/* ─────────────────────────────
   MAIN COURSE TYPE
───────────────────────────── */
export interface CourseCreate {
    courseId?: string;

    title: string;
    tagline: string;
    description: string;

    instructor: string;
    schedule: string;
    location: string;

    startDate: Date;

    duration: string;
    totalSeats: number;

    thumbnailUrl: string;
    thumbnailFile?: File | null;

    status: CourseStatus;

    price: number;
    originalPrice: number;

    discountStarts: Date | null;
    discountEnds: Date | null;

    includes: string[];

    modules: CourseModule[];
}